version: "3"
services:
  app:
    image: monitoring-demo:latest
    container_name: 'monitoring-demo'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - '8080:8080'
  app_node2:
    image: monitoring-demo:latest
    container_name: 'monitoring-demo-node2'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - '8081:8080'
  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: 'prometheus'
    volumes:
    - ./monitoring/prometheus/:/etc/prometheus/
    ports:
    - '9090:9090'
  grafana:
    image: grafana/grafana:7.4.3
    container_name: 'grafana'
    ports:
    - '3000:3000'
    volumes:
    - ./monitoring/grafana/:/etc/grafana/
    env_file:
    - ./monitoring/grafana/config.monitoring
    environment:
    - GF_INSTALL_PLUGINS=snuids-trafficlights-panel
    depends_on:
    - prometheus
  fake-smtp:
    image: munkyboy/fakesmtp
    container_name: fake-smtp
    ports: 
      - "25:25"
    volumes:
      - ~/fake-smtp-emails:/var/mail
  fake-smtp-web:
    image: mjstewart/fakesmtp-web:1.3
    container_name: fake-smtp-web
    ports: 
      - "60500:8080"
    volumes:
      - ~/fake-smtp-emails:/var/mail
    environment:
      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
    depends_on:
      - fake-smtp
