{
 "title": "MyMonitor",
 "time": { "from": "2021-03-03T12:35:08.589Z", "to": "2021-03-03T12:55:08.589Z" },
 "refresh": "30s",
 "panels": [
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Web Server Health",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "up{instance=\"monitoring-demo:8080\",job=\"monitoring-demo\"}",
     "legendFormat": "Node 1"
    },
    {
     "expr": "up{instance=\"monitoring-demo-node2:8080\",job=\"monitoring-demo\"}",
     "legendFormat": "Node 2"
    }
   ]
  },
  {
   "title": "Order Purchase",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(order_purchase_total{instance=\"monitoring-demo:8080\",job=\"monitoring-demo\"}[24h])",
     "legendFormat": "Node1"
    },
    {
     "expr": "increase(order_purchase_total{instance=\"monitoring-demo-node2:8080\",job=\"monitoring-demo\"}[24h])",
     "legendFormat": "Node2"
    }
   ]
  },
  {
   "title": "Log Counter - Node2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{instance=\"monitoring-demo-node2:8080\"}[1m])"
    }
   ]
  },
  {
   "title": "Log Counter - Node1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{instance=\"monitoring-demo:8080\"}[1m])"
    }
   ]
  },
  {
   "title": "Jvm Node 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"monitoring-demo:8080\", area=\"heap\"})/1024",
     "legendFormat": "jvm_memory_used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"monitoring-demo:8080\", area=\"heap\"})/1024",
     "legendFormat": "jvm_memory_used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"monitoring-demo:8080\", area=\"heap\"})/1024",
     "legendFormat": "jvm_memory_max"
    }
   ]
  },
  {
   "title": "Jvm Node 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"monitoring-demo-node2:8080\", area=\"heap\"})/1024",
     "legendFormat": "jvm_memory_used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"monitoring-demo-node2:8080\", area=\"heap\"})/1024",
     "legendFormat": "jvm_memory_used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"monitoring-demo-node2:8080\", area=\"heap\"})/1024",
     "legendFormat": "jvm_memory_max"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"monitoring-demo:8080\"}*100"
    }
   ]
  },
  {
   "title": "jvm_memory_used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"monitoring-demo:8080\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"monitoring-demo:8080\", area=\"heap\"})",
     "legendFormat": "Node 1"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"monitoring-demo-node2:8080\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{instance=\"monitoring-demo-node2:8080\", area=\"heap\"})",
     "legendFormat": "Node 2"
    }
   ]
  },
  {
   "title": "Req/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"monitoring-demo:8080\"}[1m]))",
     "legendFormat": "Node1"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"monitoring-demo-node2:8080\"}[1m]))",
     "legendFormat": "Node 2"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 33 },
   "options": {
    "content": "<br>\n<br>\n<strong>Node 1</strong><br>\n<br>\n<strong>Node 2</strong>\n"
   }
  },
  {
   "title": "process_start_time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 2, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"monitoring-demo:8080\"}*1000",
     "legendFormat": "Node1"
    },
    {
     "expr": "process_start_time_seconds{instance=\"monitoring-demo-node2:8080\"}*1000",
     "legendFormat": "Node 2"
    }
   ]
  },
  {
   "title": "UpTime seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"monitoring-demo:8080\"}",
     "legendFormat": "Node1"
    },
    {
     "expr": "process_uptime_seconds{instance=\"monitoring-demo-node2:8080\"}",
     "legendFormat": "Node2"
    }
   ]
  },
  {
   "title": "Restart",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resets(process_uptime_seconds{instance=\"monitoring-demo:8080\"}[1m]) > 0",
     "legendFormat": "Node1"
    },
    {
     "expr": "resets(process_uptime_seconds{instance=\"monitoring-demo-node2:8080\"}[1m]) > 0",
     "legendFormat": "Node2"
    }
   ]
  }
 ]
}